### ISSUE TITLE
Inverse Phantoms source code

### ISSUE THREAD

**Issue by tesseract-two** [Unknown-User2/Unknown-User2#3]
Would you mind publishing the source code for [Inverse Phantoms](https://modrinth.com/mod/inverse-phantoms)? (I know you don't have to under the unlicense).

**Comment by z3roco01** [comment]
yea i just published it here [https://github.com/z3roco01/Inverse-Phantoms](https://github.com/z3roco01/Inverse-Phantoms) srry i didnt see this earlier

**Comment by tesseract-two** [comment]
No problem, and thank you!
